# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed6385b8a6053231e59e208482d69fb74194f1cf45f0f562f0b35cd704ffa689f503828f1906d6428f2f12dd9255c638d64560752bc85616ab36e38d8903bc9f

test:
  secret_key_base: 5cacc0fd77a854cc0e993b6e3b9cf00d646ef67f5da1bcce7e3fde8e51fd728394f7bf4499de30aa0fa6339b2cadc5a062ff3db5870e2bf78da35f881ef6daec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
